### ISSUE TITLE
should we remove how_long comparison from git?

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/lightsource2-recipes#379]
Right now, we check if a package has been changed two places
- using git [here](https://github.com/NSLS-II/lightsource2-recipes/blob/master/scripts/nsls2-tag-build.sh#L21)
- in the docker [here](https://github.com/NSLS-II/lightsource2-recipes/blob/master/scripts/nsls2-tag-build.sh#L76) . This ultimately searches using build.py , somewhere, i think [here](https://github.com/NSLS-II/lightsource2-recipes/blob/master/scripts/build.py#L223).

Should we move the logic in build.py that checks for built files out of the docker and go through the full list of files for building? This might utlimately be safer, and I don't think we have anything to lose by cycling through the full list.

@mrakitin what do you think?

**Comment by mrakitin** [comment]
I'm still thinking we need to artificially limit the number of packages attempted to build within a run, introduced in https://github.com/NSLS-II/lightsource2-recipes/pull/351, since `build.py` will still be executed within a Docker container with all corresponding preparation of the environment (takes about a minute for each package). An updated Docker config (see https://github.com/mrakitin/debian-with-miniconda/blob/master/Dockerfile) will help to minimize the preparation/installation part to 15 seconds. We have 146 packages as of today. Still working on balancing things.

**Comment by jrmlhermitte** [comment]
I understand. After discussion that makes sense. I didn't know you added the git trick but that's a great idea!
@tacaswell suggested to on top of this force a manual build of the whole system daily just in case. I think that's a good idea.

great work @mrakitin !

**Comment by mrakitin** [comment]
@jrmlhermitte, nice, yes, the git trick is here: https://github.com/NSLS-II/lightsource2-recipes/blob/3f21d7e14422073e51feb062c65dbb7de22dc055/scripts/nsls2-tag-build.sh#L22

See https://github.com/NSLS-II/debian-with-miniconda/pull/6 for the faster Docker image.
