### ISSUE TITLE
Sort out ipywidgets version problem

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/lightsource2-recipes#479]
In the SIX environment, ipywidgets is installed both with conda and with pip. The version installed with pip _is_ compatible with the JS frontend, but the version installed with conda is not. We should make sure that only one version gets installed for the upcoming cycle.

**Comment by mrakitin** [comment]
That was me who installed the pip-version on top of conda version at SIX due to the conda version was tightly coupled to the environment as a part of the [analysis metapackage](https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/analysis/meta.yaml), so removing it wasn't possible. We have already [pinned](https://github.com/NSLS-II/lightsource2-recipes/pull/466) the versions of `ipympl` and `ipywidgets`, so we should be good for the next cycle.

**Comment by danielballan** [comment]
To recap conversation on Slack for the record, the version of ipywidgets deployed in 2018-3.[0-2] is not compatible with the version of ipympl we are using. In https://github.com/NSLS-II/lightsource2-recipes/pull/466 we pin ipywidgets to fix that, but that never went out to SIX, so they installed the pinned version of ipywidgets over top of conda using pip.

The new environments will get a mutually-compatible set of versions with no further action needed.
