### ISSUE TITLE
Make bluesky, ophyd, databroker noarch?

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#544]
A guy from Berlin's workshop tried to install Bluesky on Windows from our conda channel, but it failed due to the packages are Linux-specific. Can we consider making them noarch? Or are there any packages, which we cannot have cross-platform?

**Comment by danielballan** [comment]
I don't know what conda's official position on 'noarch' is, but I've heard from one of the core devs that it's a regrettable feature because it may _claim_ to work on all architectures but it doesn't mean it's actually been successfully _run_ on any given architecture. Better to build arch-specific packages to be sure.

I would be in favor of getting our 1.0+ packages on conda forge, where I think we would get builds for all architectures. (Maybe @CJ-Wright has already done this?) I have previous taken the position that databroker and other packages that are highly in flux should probably _not_ be on conda-forge yet.

**Comment by CJ-Wright** [comment]
All the nsls-ii developed stack is on conda forge. I think most of them are noarch. Currently all the conda forge noarch packages are built on a Linux docker image.

I think noarch is not as bad as it seems, as it allows us to cut down on CI usage and many pure python packages have no architecture dependant issues.

**Comment by prjemian** [comment]
For what it's worth, here is what I have done recently to install on Windows10-64:

https://github.com/BCDA-APS/use_bluesky/blob/master/python_installation/windows.md

**Comment by prjemian** [comment]
That is, using pip to install from GitHub master as-if *noarch* since, practically, this code for the most part *is* noarch.

**Comment by mrakitin** [comment]
The packages were made `noach` in https://anaconda.org/nsls2forge/repo and https://anaconda.org/lightsource2-tag/repo.
